services:
  rabbitmq:
    image: rabbitmq:management
    container_name: RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - 5672:5672
      - 15672:15672
    restart: always    
  activemq:
    image: rmohr/activemq:latest
    container_name: ActiveMQ
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=root
      - ACTIVEMQ_ADMIN_PASSWORD=root
    ports:
      - 61616:61616
      - 8161:8161
    restart: always
    