services:
  rabbitmq:
    image: rabbitmq:management
    container_name: RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - 5672:5672
      - 15672:15672
    restart: always    
  activemq:
    image: apache/activemq-classic
    container_name: ActiveMQ
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=root
      - ACTIVEMQ_ADMIN_PASSWORD=root
    ports:
      - 61616:61616
      - 8161:8161
    restart: always
  kafka:
    image: apache/kafka
    container_name: Kafka
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://:9093,CONTROLLER://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9094
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - 9093:9093
      - 9094:9094
    restart: always